export interface Tool {
  id: number;
  name: string;
  slug: string;
  category: string;
  tags: string[];
  description: string;
  features: string[];
  pricing: string;
  url: string;
}

export const categories = [
  "AI Assistants",
  "APIs",
  "Analytics",
  "Databases",
  "Design",
  "Documentation",
  "Frameworks",
  "IDEs",
  "Testing",
  "DevOps",
  "Security",
  "Productivity",
] as const;

export type Category = (typeof categories)[number];

export const tools: Tool[] = [
  // Batch 1: tools 1-100 from awesome-dev-tools and awesome-devtools
  // Source citations in individual entries

  {
    id: 1,
    name: "ToolHover",
    slug: "toolhover",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "Free online developer utilities including JSON formatter & validator, password generator, hash generator, Base64 encoder/decoder, text counter & converter, and QR code generator.",
    features: [],
    pricing: "Free tier available",
    url: "https://toolhover.com",
  },
  {
    id: 2,
    name: "Visual Studio Code",
    slug: "visual-studio-code",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "A free, lightweight, cross-platform source code editor by Microsoft for Windows, Linux, and macOS, with support for debugging, syntax highlighting, intelligent code completion, Git integration, and more. Built with Electron and TypeScript.",
    features: [],
    pricing: "Free tier available",
    url: "https://code.visualstudio.com/",
  },
  {
    id: 3,
    name: "Vim",
    slug: "vim",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "a highly customizable text editor that's designed to be used entirely from the keyboard, with a focus on speed and efficiency",
    features: [],
    pricing: "Free tier available",
    url: "https://www.vim.org/",
  },
  {
    id: 4,
    name: "Neovim",
    slug: "neovim",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "a fork of Vim that provides improved performance and extensibility, while still maintaining compatibility with Vim's core features and workflows",
    features: [],
    pricing: "Free tier available",
    url: "https://neovim.io/",
  },
  {
    id: 5,
    name: "Eclipse",
    slug: "eclipse",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "An open-source IDE written in Java, mainly used for Java development but also supports other programming languages via plug-ins. Available for Windows, Linux, and macOS.",
    features: [],
    pricing: "Free tier available",
    url: "https://www.eclipse.org/",
  },
  {
    id: 6,
    name: "IntelliJ IDEA",
    slug: "intellij-idea",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "A powerful and customizable IDE for Java, Kotlin, and other programming languages, with advanced code analysis, debugging, and testing tools. Available for Windows, Linux, and macOS.",
    features: [],
    pricing: "Free tier available",
    url: "https://www.jetbrains.com/idea/",
  },
  {
    id: 7,
    name: "Sublime Text",
    slug: "sublime-text",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "A lightweight code editor used to write and edit code in various programming languages. Provides a range of features for code editing and customization. Available for Windows, Linux, and macOS.",
    features: [],
    pricing: "Free tier available",
    url: "https://www.sublimetext.com/",
  },
  {
    id: 8,
    name: "Android Studio",
    slug: "android-studio",
    category: "IDEs",
    tags: ["awesomedevtools", "ides"],
    description: "the official integrated development environment (IDE) for developing Android apps, providing a wide range of tools and features for building and testing Android applications",
    features: [],
    pricing: "Free tier available",
    url: "https://developer.android.com/studio",
  },
  {
    id: 9,
    name: "Git",
    slug: "git",
    category: "DevOps",
    tags: ["awesomedevtools", "devops"],
    description: "A free and open-source distributed version control system that allows developers to collaborate on projects and track changes to code. Available for Windows, Linux, and macOS.",
    features: [],
    pricing: "Free tier available",
    url: "https://git-scm.com/",
  },
  {
    id: 10,
    name: "Subversion",
    slug: "subversion",
    category: "DevOps",
    tags: ["awesomedevtools", "devops"],
    description: "A centralized version control system that can be used to track changes to files and directories over time. Available for Windows, Linux, and macOS.",
    features: [],
    pricing: "Free tier available",
    url: "https://subversion.apache.org/",
  },
  {
    id: 11,
    name: "Buildstash",
    slug: "buildstash",
    category: "DevOps",
    tags: ["awesomedevtools", "devops"],
    description: "A web-based platform for managing built software binaries, integrating with CI/CD to automate archival, and allowing distribution of binaries to collaborators, testers, and users.",
    features: [],
    pricing: "Free tier available",
    url: "https://buildstash.com",
  },
  {
    id: 12,
    name: "Jest",
    slug: "jest",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "a popular testing framework for JavaScript that provides a simple and easy-to-use API for writing tests",
    features: [],
    pricing: "Free tier available",
    url: "https://jestjs.io/",
  },
  {
    id: 13,
    name: "Mocha",
    slug: "mocha",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "a JavaScript testing framework that provides a flexible and extensible testing infrastructure",
    features: [],
    pricing: "Free tier available",
    url: "https://mochajs.org/",
  },
  {
    id: 14,
    name: "Xdebug",
    slug: "xdebug",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "A PHP extension for debugging PHP scripts. Available for Windows, Linux, and macOS.",
    features: [],
    pricing: "Free tier available",
    url: "https://xdebug.org/",
  },
  {
    id: 15,
    name: "JUnit",
    slug: "junit",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "A popular testing framework for Java programmers. Used for unit testing, integration testing, and more.",
    features: [],
    pricing: "Free tier available",
    url: "https://junit.org/junit5/",
  },
  {
    id: 16,
    name: "NPM Scan",
    slug: "npm-scan",
    category: "Security",
    tags: ["awesomedevtools", "security"],
    description: "Zero-setup npm package security scanner that detects malicious code, obfuscation, and supply-chain risks in dependencies.",
    features: [],
    pricing: "Free tier available",
    url: "https://npmscan.com/",
  },
  {
    id: 17,
    name: "Cypress",
    slug: "cypress",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "a JavaScript end-to-end testing framework that provides an easy-to-use API for writing tests",
    features: [],
    pricing: "Free tier available",
    url: "https://www.cypress.io/",
  },
  {
    id: 18,
    name: "Playwright",
    slug: "playwright",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "an open-source Node.js library for automating browsers and mobile devices, providing a simple and easy-to-use API for writing tests",
    features: [],
    pricing: "Free tier available",
    url: "https://playwright.dev/",
  },
  {
    id: 19,
    name: "Selenium",
    slug: "selenium",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "An open-source tool for automating web browsers to test web applications. Supports multiple programming languages and browsers.",
    features: [],
    pricing: "Free tier available",
    url: "https://www.selenium.dev/",
  },
  {
    id: 20,
    name: "Appium",
    slug: "appium",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "an open-source test automation tool for mobile applications that supports a wide range of mobile platforms and devices",
    features: [],
    pricing: "Free tier available",
    url: "http://appium.io/",
  },
  {
    id: 21,
    name: "Detox",
    slug: "detox",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "a gray-box end-to-end testing and automation framework for mobile apps that provides a simple and easy-to-use API for writing tests",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/wix/Detox",
  },
  {
    id: 22,
    name: "Beeceptor",
    slug: "beeceptor",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "A no-code, cloud based, multi-protocol mock server and debugging tool, used to create API endpoints for testing and prototyping.",
    features: [],
    pricing: "Free tier available",
    url: "https://beeceptor.com/",
  },
  {
    id: 23,
    name: "Microcks",
    slug: "microcks",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "The open source (CNCF project), cloud native and Kubernetes-native platform for mocking and testing microservices.",
    features: [],
    pricing: "Free tier available",
    url: "https://microcks.io/",
  },
  {
    id: 24,
    name: "WireMock",
    slug: "wiremock",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "Open-source, flexible multi-protocol service virtualization tool by which external dependencies can be mocked for testing purposes.",
    features: [],
    pricing: "Free tier available",
    url: "https://wiremock.org/",
  },
  {
    id: 25,
    name: "Telert",
    slug: "telert",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "Lightweight open-source CLI tool to send Telegram, Slack, Desktop, or Audio notifications when a command finishes.",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/navig-me/telert",
  },
  {
    id: 26,
    name: "Jira",
    slug: "jira",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "A proprietary issue tracking, bug tracking, and project management tool developed by Atlassian.",
    features: [],
    pricing: "Free tier available",
    url: "https://www.atlassian.com/software/jira",
  },
  {
    id: 27,
    name: "Asana",
    slug: "asana",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "A web and mobile application designed to help teams organize, track, and manage their work and tasks.",
    features: [],
    pricing: "Free tier available",
    url: "https://asana.com/",
  },
  {
    id: 28,
    name: "Trello",
    slug: "trello",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "A web-based project management tool that allows users to create boards, lists, and cards to organize tasks and collaborate with team members.",
    features: [],
    pricing: "Free tier available",
    url: "https://trello.com/",
  },
  {
    id: 29,
    name: "ByteTools JWT Decoder",
    slug: "bytetools-jwt-decoder",
    category: "Security",
    tags: ["awesomedevtools", "security"],
    description: "Decode and inspect JSON Web Tokens securely. 100% client-side processing.",
    features: [],
    pricing: "Free tier available",
    url: "https://bytetools.io/jwt-decoder/",
  },
  {
    id: 30,
    name: "ByteTools Passphrase Generator",
    slug: "bytetools-passphrase-generator",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "Generate secure, memorable passphrases with customizable options.",
    features: [],
    pricing: "Free tier available",
    url: "https://bytetools.io/passphrase-generator/",
  },
  {
    id: 31,
    name: "ByteTools QR Generator",
    slug: "bytetools-qr-generator",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "Generate QR codes including WiFi QR codes. Works offline.",
    features: [],
    pricing: "Free tier available",
    url: "https://bytetools.io/qr-generator/",
  },
  {
    id: 32,
    name: "ByteTools Regex Test",
    slug: "bytetools-regex-test",
    category: "Testing",
    tags: ["awesomedevtools", "testing"],
    description: "Free regex test tool with real-time matching and examples.",
    features: [],
    pricing: "Free tier available",
    url: "https://bytetools.io/regex-tester/",
  },
  {
    id: 33,
    name: "ByteTools URL Encoder",
    slug: "bytetools-url-encoder",
    category: "Productivity",
    tags: ["awesomedevtools", "productivity"],
    description: "Encode and decode URLs safely for query parameters and API endpoints.",
    features: [],
    pricing: "Free tier available",
    url: "https://bytetools.io/url-encoder/",
  },
  {
    id: 34,
    name: "React",
    slug: "react",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a JavaScript library for building user interfaces",
    features: [],
    pricing: "Free tier available",
    url: "https://reactjs.org/",
  },
  {
    id: 35,
    name: "Vue.js",
    slug: "vuejs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a progressive JavaScript framework for building user interfaces",
    features: [],
    pricing: "Free tier available",
    url: "https://vuejs.org/",
  },
  {
    id: 36,
    name: "Angular",
    slug: "angular",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a TypeScript-based open-source web application framework",
    features: [],
    pricing: "Free tier available",
    url: "https://angular.io/",
  },
  {
    id: 37,
    name: "Nuxt.js",
    slug: "nuxtjs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a higher-level framework based on Vue.js for building server-rendered web applications",
    features: [],
    pricing: "Free tier available",
    url: "https://nuxtjs.org/",
  },
  {
    id: 38,
    name: "Svelte",
    slug: "svelte",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a front-end framework that compiles your code to highly efficient JavaScript, with no virtual DOM",
    features: [],
    pricing: "Free tier available",
    url: "https://svelte.dev/",
  },
  {
    id: 39,
    name: "Solid.js",
    slug: "solidjs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a fast, reactive JavaScript library for building user interfaces, inspired by React and Vue",
    features: [],
    pricing: "Free tier available",
    url: "https://www.solidjs.com/",
  },
  {
    id: 40,
    name: "Next.js",
    slug: "nextjs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a React-based framework for building server-rendered web applications",
    features: [],
    pricing: "Free tier available",
    url: "https://nextjs.org/",
  },
  {
    id: 41,
    name: "Ruby on Rails",
    slug: "ruby-on-rails",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a popular web framework for the Ruby programming language",
    features: [],
    pricing: "Free tier available",
    url: "https://rubyonrails.org/",
  },
  {
    id: 42,
    name: "Django",
    slug: "django",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a high-level Python web framework that encourages rapid development and clean, pragmatic design",
    features: [],
    pricing: "Free tier available",
    url: "https://www.djangoproject.com/",
  },
  {
    id: 43,
    name: "Express.js",
    slug: "expressjs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a fast, unopinionated, minimalist web framework for Node.js",
    features: [],
    pricing: "Free tier available",
    url: "https://expressjs.com/",
  },
  {
    id: 44,
    name: "Flask",
    slug: "flask",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a lightweight Python web framework that's easy to learn and use",
    features: [],
    pricing: "Free tier available",
    url: "https://flask.palletsprojects.com/",
  },
  {
    id: 45,
    name: "Spring",
    slug: "spring",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a Java framework for building web and enterprise applications",
    features: [],
    pricing: "Free tier available",
    url: "https://spring.io/",
  },
  {
    id: 46,
    name: "ASP.NET",
    slug: "aspnet",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a popular web framework for building web applications with .NET",
    features: [],
    pricing: "Free tier available",
    url: "https://dotnet.microsoft.com/apps/aspnet",
  },
  {
    id: 47,
    name: "Laravel",
    slug: "laravel",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a PHP web framework with expressive, elegant syntax and a focus on developer happiness",
    features: [],
    pricing: "Free tier available",
    url: "https://laravel.com/",
  },
  {
    id: 48,
    name: "React Native",
    slug: "react-native",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a JavaScript framework for building native mobile apps using React",
    features: [],
    pricing: "Free tier available",
    url: "https://reactnative.dev/",
  },
  {
    id: 49,
    name: "Flutter",
    slug: "flutter",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "an open-source UI software development kit created by Google for building natively compiled applications for mobile, web, and desktop from a single codebase",
    features: [],
    pricing: "Free tier available",
    url: "https://flutter.dev/",
  },
  {
    id: 50,
    name: "Ionic",
    slug: "ionic",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a cross-platform mobile app development framework based on Angular",
    features: [],
    pricing: "Free tier available",
    url: "https://ionicframework.com/",
  },
  {
    id: 51,
    name: "Xamarin",
    slug: "xamarin",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a Microsoft-owned platform for building native Android, iOS, and Windows apps with .NET and C#",
    features: [],
    pricing: "Free tier available",
    url: "https://dotnet.microsoft.com/apps/xamarin",
  },
  {
    id: 52,
    name: "NativeScript",
    slug: "nativescript",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "an open-source framework for building native mobile apps with Angular, Vue.js, or TypeScript",
    features: [],
    pricing: "Free tier available",
    url: "https://nativescript.org/",
  },
  {
    id: 53,
    name: "Retool Mobile",
    slug: "retool-mobile",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "Retool Mobile is a no-code tool that makes building native iOS and Android apps fast.",
    features: [],
    pricing: "Free tier available",
    url: "https://retool.com/",
  },
  {
    id: 54,
    name: "Figma",
    slug: "figma",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "a cloud-based design tool for creating user interfaces, providing a powerful and collaborative design environment",
    features: [],
    pricing: "Free tier available",
    url: "https://www.figma.com/",
  },
  {
    id: 55,
    name: "Sketch",
    slug: "sketch",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "a digital design tool for creating user interfaces, providing a range of vector editing features and collaboration tools",
    features: [],
    pricing: "Free tier available",
    url: "https://www.sketch.com/",
  },
  {
    id: 56,
    name: "Adobe XD",
    slug: "adobe-xd",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "a vector-based design tool for creating user interfaces and experiences, providing features for prototyping and collaboration",
    features: [],
    pricing: "Free tier available",
    url: "https://www.adobe.com/products/xd.html",
  },
  {
    id: 57,
    name: "CSS Modules",
    slug: "css-modules",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a CSS methodology and tool for locally-scoped CSS, making it easier to manage styles in large applications",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/css-modules/css-modules",
  },
  {
    id: 58,
    name: "CSS-in-JS",
    slug: "css-in-js",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a technique for writing and managing styles in JavaScript, allowing for dynamic styling and better maintainability",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/cssinjs/",
  },
  {
    id: 59,
    name: "Sass",
    slug: "sass",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a popular CSS preprocessor that provides more advanced features, such as variables, nesting, and mixins",
    features: [],
    pricing: "Free tier available",
    url: "https://sass-lang.com/",
  },
  {
    id: 60,
    name: "SCSS",
    slug: "scss",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a more modern version of Sass that uses a syntax that's closer to traditional CSS",
    features: [],
    pricing: "Free tier available",
    url: "https://sass-lang.com/documentation/syntax#scss",
  },
  {
    id: 61,
    name: "Less",
    slug: "less",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a CSS preprocessor that provides a simpler syntax than Sass, but still offers many advanced features",
    features: [],
    pricing: "Free tier available",
    url: "http://lesscss.org/",
  },
  {
    id: 62,
    name: "PostCSS",
    slug: "postcss",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a CSS postprocessor that can transform your CSS in a variety of ways, including adding vendor prefixes and optimizing styles",
    features: [],
    pricing: "Free tier available",
    url: "https://postcss.org/",
  },
  {
    id: 63,
    name: "Headless UI",
    slug: "headless-ui",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a set of completely unstyled, fully accessible UI components for building web applications with React or Vue",
    features: [],
    pricing: "Free tier available",
    url: "https://headlessui.dev/",
  },
  {
    id: 64,
    name: "Chakra UI",
    slug: "chakra-ui",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a popular React component library with a focus on accessibility and ease of use",
    features: [],
    pricing: "Free tier available",
    url: "https://chakra-ui.com/",
  },
  {
    id: 65,
    name: "Tailwind CSS",
    slug: "tailwind-css",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a utility-first CSS framework that provides a set of pre-defined styles and classes for building web applications",
    features: [],
    pricing: "Free tier available",
    url: "https://tailwindcss.com/",
  },
  {
    id: 66,
    name: "Materialize",
    slug: "materialize",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "A modern responsive front-end framework based on Google's Material Design. Includes CSS and JavaScript components.",
    features: [],
    pricing: "Free tier available",
    url: "https://materializecss.com/",
  },
  {
    id: 67,
    name: "Framer Motion",
    slug: "framer-motion",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "a production-ready motion library for React, used to create animations and gestures in web applications",
    features: [],
    pricing: "Free tier available",
    url: "https://www.framer.com/motion/",
  },
  {
    id: 68,
    name: "GreenSock Animation Platform (GSAP)",
    slug: "gsap",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "A high-performance animation library for HTML5 and JavaScript, with support for complex animations and interactivity",
    features: [],
    pricing: "Free tier available",
    url: "https://greensock.com/gsap/",
  },
  {
    id: 69,
    name: "Anime.js",
    slug: "animejs",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "A lightweight animation library for JavaScript, with support for CSS properties, SVG, and DOM attributes",
    features: [],
    pricing: "Free tier available",
    url: "https://animejs.com/",
  },
  {
    id: 70,
    name: "Three.js",
    slug: "threejs",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "A lightweight 3D animation library for JavaScript, used to create 3D animations and visualizations in the browser",
    features: [],
    pricing: "Free tier available",
    url: "https://threejs.org/",
  },
  {
    id: 71,
    name: "Lottie",
    slug: "lottie",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "an open-source library for rendering After Effects animations in real-time on the web and in mobile apps",
    features: [],
    pricing: "Free tier available",
    url: "https://airbnb.io/lottie/",
  },
  {
    id: 72,
    name: "Snap.svg",
    slug: "snap-svg",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "A JavaScript library for creating and animating SVG graphics on the web. Available for free download.",
    features: [],
    pricing: "Free tier available",
    url: "http://snapsvg.io/",
  },
  {
    id: 73,
    name: "D3.js",
    slug: "d3js",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "A JavaScript library for creating dynamic and interactive data visualizations in web browsers",
    features: [],
    pricing: "Free tier available",
    url: "https://d3js.org/",
  },
  {
    id: 74,
    name: "Raphael.js",
    slug: "raphaeljs",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "A lightweight JavaScript library for working with vector graphics on the web. Available for free download.",
    features: [],
    pricing: "Free tier available",
    url: "http://dmitrybaranovskiy.github.io/raphael/",
  },
  {
    id: 75,
    name: "SVGO",
    slug: "svgo",
    category: "Design",
    tags: ["awesomedevtools", "design"],
    description: "an open-source tool for optimizing SVG files, providing a wide range of optimization options for reducing file size",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/svg/svgo",
  },
  {
    id: 76,
    name: "TipTap",
    slug: "tiptap",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a framework for building rich text editors in Vue.js, providing a powerful and flexible set of tools for creating custom editors",
    features: [],
    pricing: "Free tier available",
    url: "https://www.tiptap.dev/",
  },
  {
    id: 77,
    name: "Draft.js",
    slug: "draftjs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "an open-source library for building rich text editors in React, providing a powerful and flexible set of tools for creating custom editors",
    features: [],
    pricing: "Free tier available",
    url: "https://draftjs.org/",
  },
  {
    id: 78,
    name: "Lexical",
    slug: "lexical",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a JavaScript library for building custom text editors, providing a simple and extensible API for creating rich text editors",
    features: [],
    pricing: "Free tier available",
    url: "https://lexical.ooo/",
  },
  {
    id: 79,
    name: "Editor.js",
    slug: "editorjs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a block-based editor for creating articles, blog posts, and other rich content, providing a simple and easy-to-use interface",
    features: [],
    pricing: "Free tier available",
    url: "https://editorjs.io/",
  },
  {
    id: 80,
    name: "ProseMirror",
    slug: "prosemirror",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a toolkit for building rich-text editors in the browser, providing a powerful and flexible set of tools for creating custom editors",
    features: [],
    pricing: "Free tier available",
    url: "https://prosemirror.net/",
  },
  {
    id: 81,
    name: "Slate.js",
    slug: "slatejs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a completely customizable framework for building rich-text editors, providing a simple and extensible API for creating custom editors",
    features: [],
    pricing: "Free tier available",
    url: "https://www.slatejs.org/",
  },
  {
    id: 82,
    name: "Editable.js",
    slug: "editablejs",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "a library for creating in-browser WYSIWYG editors, providing a simple and easy-to-use interface for editing content",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/medialize/Editable.js",
  },
  {
    id: 83,
    name: "Polymer",
    slug: "polymer",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "A JavaScript library for building web components and creating reusable custom elements for web applications",
    features: [],
    pricing: "Free tier available",
    url: "https://polymer-library.polymer-project.org/",
  },
  {
    id: 84,
    name: "LitElement",
    slug: "litelement",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "A lightweight web component library built on top of Polymer, used to create and reuse custom HTML elements",
    features: [],
    pricing: "Free tier available",
    url: "https://lit-element.polymer-project.org/",
  },
  {
    id: 85,
    name: "Tauri",
    slug: "tauri",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "an open-source framework for building cross-platform desktop applications with web technologies like HTML, CSS, and JavaScript",
    features: [],
    pricing: "Free tier available",
    url: "https://tauri.studio/",
  },
  {
    id: 86,
    name: "Electron",
    slug: "electron",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "A popular framework for building cross-platform desktop applications using web technologies like HTML, CSS, and JavaScript",
    features: [],
    pricing: "Free tier available",
    url: "https://www.electronjs.org/",
  },
  {
    id: 87,
    name: "Qt",
    slug: "qt",
    category: "Frameworks",
    tags: ["awesomedevtools", "frameworks"],
    description: "A comprehensive, cross-platform C++ application development framework used to create applications with a native look and feel",
    features: [],
    pricing: "Free tier available",
    url: "https://www.qt.io/",
  },
  {
    id: 88,
    name: "MySQL",
    slug: "mysql",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "An open-source relational database management system that supports SQL queries and provides a reliable and efficient way to store and retrieve data",
    features: [],
    pricing: "Free tier available",
    url: "https://www.mysql.com/",
  },
  {
    id: 89,
    name: "PostgreSQL",
    slug: "postgresql",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "A powerful, open-source object-relational database management system that supports a wide range of data types and provides advanced features for data storage and retrieval",
    features: [],
    pricing: "Free tier available",
    url: "https://www.postgresql.org/",
  },
  {
    id: 90,
    name: "MongoDB",
    slug: "mongodb",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "A document-based NoSQL database that uses JSON-like documents to store data. Supports flexible schema and horizontal scaling.",
    features: [],
    pricing: "Free tier available",
    url: "https://www.mongodb.com/",
  },
  {
    id: 91,
    name: "Couchbase",
    slug: "couchbase",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "A distributed NoSQL database that uses key-value pairs to store and retrieve data, with support for SQL-like queries",
    features: [],
    pricing: "Free tier available",
    url: "https://www.couchbase.com/",
  },
  {
    id: 92,
    name: "tbls",
    slug: "tbls",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "tbls is a CI-Friendly tool for document a database, written in Go.",
    features: [],
    pricing: "Free tier available",
    url: "https://github.com/k1LoW/tbls",
  },
  {
    id: 93,
    name: "Tableau",
    slug: "tableau",
    category: "Analytics",
    tags: ["awesomedevtools", "analytics"],
    description: "A powerful data visualization tool used to explore and analyze data in various formats, providing interactive dashboards and reports",
    features: [],
    pricing: "Free tier available",
    url: "https://www.tableau.com/",
  },
  {
    id: 94,
    name: "Power BI",
    slug: "power-bi",
    category: "Analytics",
    tags: ["awesomedevtools", "analytics"],
    description: "A cloud-based business analytics service by Microsoft that provides interactive visualizations and business intelligence capabilities",
    features: [],
    pricing: "Free tier available",
    url: "https://powerbi.microsoft.com/",
  },
  {
    id: 95,
    name: "Databricks",
    slug: "databricks",
    category: "Analytics",
    tags: ["awesomedevtools", "analytics"],
    description: "A cloud-based data engineering, data science, and analytics platform used to build and deploy machine learning models",
    features: [],
    pricing: "Free tier available",
    url: "https://databricks.com/",
  },
  {
    id: 96,
    name: "Strapi",
    slug: "strapi",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "an open-source headless CMS that provides a flexible content management system and API for building web and mobile applications",
    features: [],
    pricing: "Free tier available",
    url: "https://strapi.io/",
  },
  {
    id: 97,
    name: "Contentful",
    slug: "contentful",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "a cloud-based headless CMS that offers a variety of content management tools and APIs for building web and mobile applications",
    features: [],
    pricing: "Free tier available",
    url: "https://www.contentful.com/",
  },
  {
    id: 98,
    name: "Sanity",
    slug: "sanity",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "a headless CMS that provides a real-time collaborative editing environment, as well as a powerful API for building web and mobile applications",
    features: [],
    pricing: "Free tier available",
    url: "https://www.sanity.io/",
  },
  {
    id: 99,
    name: "Prismic",
    slug: "prismic",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "a headless CMS that offers a flexible content model and API, with a focus on user experience and ease of use",
    features: [],
    pricing: "Free tier available",
    url: "https://prismic.io/",
  },
  {
    id: 100,
    name: "Umbraco",
    slug: "umbraco",
    category: "Databases",
    tags: ["awesomedevtools", "databases"],
    description: "an open-source content management system that provides a flexible and extensible platform for building web applications",
    features: [],
    pricing: "Free tier available",
    url: "https://umbraco.com/",
  },
];

export const allTags = Array.from(new Set(tools.flatMap((t) => t.tags))).sort();
